apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf0
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.222.0/24",
        "rangeStart": "192.168.222.200",
        "rangeEnd": "192.168.222.209",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.222.1"
      }
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf1
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.222.0/24",
        "rangeStart": "192.168.222.210",
        "rangeEnd": "192.168.222.219",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.222.1"
      }
    }'
