---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod0
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf0
spec:
  containers:
  - name: samplepod0
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    image: kubernetes-master:5000/busybox:1.29
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf1
spec:
  containers:
  - name: samplepod1
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    image: kubernetes-master:5000/busybox:1.29
    ports:
    - containerPort: 80
